export const START_LOADING = "START_LOADING";
export const FINISH_LOADING = "FINISH_LOADING";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOG_OUT_SUCCESS = "LOG_OUT_SUCCESS";

export const SET_ADMIN_DATA = "SET_ADMIN_DATA";
export const REMOVE_ADMIN_DATA = "SET_ADMIN_DATA";